name: 💡 Idea
description: Suggest a feature
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What you want
      description: What problem it solves and how you see it working
    validations:
      required: true
