"""Generates doc pages from code: command reference and module examples, in English and Russian.

python scripts/gen_docs.py          # rewrite docs/{commands,examples}{,.ru}.md
python scripts/gen_docs.py --check  # only check they're up to date (same as tests/test_docs.py)
"""

from __future__ import annotations

import asyncio
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from uroboros.database import Database  # noqa: E402
from uroboros.loader import Loader  # noqa: E402
from uroboros.security import LEVEL_NAMES  # noqa: E402

DOCS = ROOT / "docs"
EXAMPLES = ROOT / "examples"
NOTICE = "<!-- Generated by scripts/gen_docs.py from code, do not edit. -->\n\n"

TEXT = {
    "en": {
        "commands_title": "# Commands\n\n",
        "commands_intro": (
            "Built-in Uroboros commands. The default prefix is a dot; change it with `.setprefix`. "
            "Access is who besides this account may run the command (see [Security](security.md)); "
            "change it with `.security <command> <level>`. Descriptions are in Russian until the bot is translated.\n"
        ),
        "commands_header": "| Command | Description | Access |\n|---|---|---|\n",
        "examples_title": "# Module examples\n\n",
        "examples_intro": (
            "Every example is loaded in tests (`tests/test_examples.py`), so the code works with the current version. "
            "Install one by replying to the file with `.lm` or with `.dlm asykixd/uroboros/examples/<name>`.\n"
        ),
    },
    "ru": {
        "commands_title": "# Команды\n\n",
        "commands_intro": (
            "Встроенные команды Uroboros. Префикс по умолчанию — точка, меняется командой `.setprefix`. "
            "Доступ — кто ещё, кроме этого аккаунта, может вызвать команду (см. [Безопасность](security.md)); "
            "права меняются командой `.security <команда> <уровень>`.\n"
        ),
        "commands_header": "| Команда | Что делает | Доступ |\n|---|---|---|\n",
        "examples_title": "# Примеры модулей\n\n",
        "examples_intro": (
            "Каждый пример загружается в тестах (`tests/test_examples.py`), "
            "поэтому код ниже рабочий для текущей версии. "
            "Установить пример: ответьте на файл командой `.lm` или `.dlm asykixd/uroboros/examples/<имя>`.\n"
        ),
    },
}
SUFFIX = {"en": "", "ru": ".ru"}


def cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


async def _commands(lang: str) -> str:
    text = TEXT[lang]
    with tempfile.TemporaryDirectory() as tmp:
        db = Database(":memory:")
        loader = Loader(None, db, Path(tmp) / "modules")
        await loader.load_all()
        parts = [text["commands_title"], NOTICE, text["commands_intro"]]
        for module in sorted(loader.modules.values(), key=lambda m: m.name.lower()):
            commands = sorted(loader.module_commands(module), key=lambda c: c.name)
            if not commands:
                continue
            parts.append(f"\n## {module.name}\n\n{(type(module).__doc__ or '').strip()}\n\n")
            parts.append(text["commands_header"])
            for cmd in commands:
                args, _, about = cmd.info.doc.partition("— ")
                usage = f"`.{cmd.name}{(' ' + args.strip()) if args.strip() else ''}`"
                if cmd.info.emoji:
                    usage = f"{cmd.info.emoji} {usage}"
                if cmd.info.aliases:
                    usage += " (" + ", ".join(f"`.{alias}`" for alias in cmd.info.aliases) + ")"
                parts.append(
                    f"| {cell(usage)} | {cell(about.strip() or cmd.info.doc)} | {LEVEL_NAMES[cmd.info.access]} |\n"
                )
        await loader.unload_all()
        db.close()
    return "".join(parts)


def _examples(lang: str) -> str:
    parts = [TEXT[lang]["examples_title"], NOTICE, TEXT[lang]["examples_intro"]]
    for path in sorted(EXAMPLES.glob("*.py")):
        source = path.read_text("utf-8")
        parts.append(f"\n## {path.stem}\n\n```python\n{source.rstrip()}\n```\n")
    return "".join(parts)


def generate() -> dict[Path, str]:
    pages = {}
    for lang, suffix in SUFFIX.items():
        pages[DOCS / f"commands{suffix}.md"] = asyncio.run(_commands(lang))
        pages[DOCS / f"examples{suffix}.md"] = _examples(lang)
    return pages


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    for path, text in generate().items():
        if path.exists() and path.read_text("utf-8") == text:
            continue
        stale.append(path)
        if not check:
            path.write_text(text, "utf-8")
    if check and stale:
        print("Stale:", ", ".join(str(p.relative_to(ROOT)) for p in stale), "- run scripts/gen_docs.py")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
